### ISSUE TITLE
Testing webhooks in request specs.

### ISSUE THREAD

**Issue by pat** [integrallis/stripe_event#100]
After updating to v2.0.0, I found my webhook tests failing, for two reasons:

* They now need to have the HMAC'd signature
* The full event object is sent through, rather than just an id (I believe this might be a much older change by Stripe, though?)

Figure it might be helpful for others to share [my solution](https://github.com/pat/drumknott-server/commit/78351a5679c4130df2e398e305495636e07ea290):

```ruby
def post_webhook(event)
  timestamp = Time.current.to_i.to_s
  data      = event.to_json
  signature = OpenSSL::HMAC.hexdigest(
    OpenSSL::Digest.new("sha256"),
    StripeEvent.signing_secret,
    "#{timestamp}.#{data}"
  )

  post "/hooks/stripe",
    :params  => data,
    :headers => {"Stripe-Signature" => "t=#{timestamp}, v1=#{signature}"}
end
```

Perhaps this is useful for your docs? Or to link to? At least it's here in this issue for others to wander across in their searches for how others have done things :)

Thanks for keeping the gem up-to-date with Stripe's evolving API!

**Comment by rmm5t** [comment]
Hi @pat. Thanks for sharing!

> The full event object is sent through, rather than just an id (I believe this might be a much older change by Stripe, though?)

The full event was always sent, but it couldn't be trusted before. This is why stripe_event v1.x always issued a separate network call to fetch the event from the Stripe API before trusting an event. With signatures, this extra network call is no longer necessary.

We do have a [note about testing in the README](https://github.com/integrallis/stripe_event#testing); however, the current approach documented there is a Mockist's approach. Yours is more of a Classicist's approach (which I personally prefer over mocking), and is what [our internal tests here employ](https://github.com/integrallis/stripe_event/blob/master/spec/controllers/webhook_controller_spec.rb#L13-L19).
