### ISSUE TITLE
Where to put Subscriber objects that respond to call?

### ISSUE THREAD

**Issue by timokleemann** [integrallis/stripe_event#108]
Hey,

I'm curious to hear where you guys normally put the Subscriber objects that respond to `#call`: 

```
class CustomerCreated
  def call(event)
    # Event handling
  end
end
```

I usually keep them in a folder `app/stripe_handlers`, however that will produce the following error every now and then:

`ArgumentError (A copy of PaymentFailed has been removed from the module tree but is still active!)`

I guess that's because everything inside `app` is constantly being reloaded by Rails while the `StripeEvent.configure` bits in the initializer are not?

**Comment by rmm5t** [comment]
I don't think there's any definitive convention here, but here is a `tree` of the relevant files in my repository. I put all my subscribers under a `StripeEvents` module namespace.

```
app
├── lib
│   ├── stripe_events
│   │   ├── account_application_deauthorized.rb
│   │   ├── account_updated.rb
│   │   ├── charge_refunded.rb
│   │   ├── customer_subscription_deleted.rb
│   │   ├── event_retriever.rb
│   │   ├── invoice_created.rb
│   │   ├── invoice_payment_failed.rb
│   │   ├── invoice_payment_succeeded.rb
│   │   └── logger.rb
│   └── stripe_events.rb
```

----

However, this won't likely remedy your `ArgumentError` problem. There are just cases where you need to reload your development environment.

**Comment by timokleemann** [comment]
OK, thanks a lot. So your `stripe_events.rb` contains your `Stripe.configure` block then?

```
StripeEvent.configure do |events|
  events.all BillingEventLogger.new(Rails.logger)
  events.subscribe 'customer.created', CustomerCreated.new
end
```

**Comment by rmm5t** [comment]
@timokleemann No, my `StripeEvent.configure` exists in `config/initializers/stripe.rb`

**Comment by jasonkarns** [comment]
FYI, as a workaround to the `ArgumentError`, we've wrapped our callables in lambdas so that those instances aren't held in the StripeEvent backend across Rails reloads.

ie:

```
StripeEvent.configure do |config|
  config.subscribe 'customer.subscription.created', ->(event) { RecordStripeSubscription.new.call event }
end
```

Hopefully I can take a stab at a PR to fix the issue directly and eliminate the need for the workaround. But in the interim...

**Comment by timokleemann** [comment]
Nice input, thanks a lot. I'm still reading and trying to figure out how all this works. Thankfully, I am getting the `Argument Error` only occasionally in development mode. It hasn't affected my production environment so far.

**Comment by gregblass** [comment]
Hey there. I just ran into this.

I have my StripeEvent.configure in my stripe.rb file (app/config/initializers/stripe.rb), but it's doing some really strange stuff - like requiring me to restart my development server if I change my service object code, or throwing an Argument error if I hit the same event for a 2nd time.

I'm going to try to refactor my file structure as recommended above, and implement that |config| lambda and see if it hit helps.

I'll report back on my findings, then maybe I'll take a stab at a readme update PR.

**Comment by gregblass** [comment]
@jasonkarns Your solution worked great for me - thank you. Something should probably be added to the readme about this.

**Comment by tolgap** [comment]
For anyone that might run into this issue, this is the setup I have right now:

A `base_event.rb` that acts as a concern which responds to `.call` on class level:

```ruby
# base_event.rb
module BaseEvent
  extend ActiveSupport::Concern

  class_methods do
    def call(event)
      handler = new(event.data.object)
      method = event.type.split('.').drop(1).join('_').to_sym
      handler.send(method) if handler.respond_to?(method)
    end
  end
end
```

And then I have `CustomerEvent` and `InvoiceEvent` classes that include `BaseEvent`. These are classes that have corresponding methods to the event that fires. `customer.subscription.created` will be called as `CustomerEvent#subscription_created`. `customer.updated` will be called as `CustomerEvent.updated` (given that you implement the actual method on the `CustomerEvent` class):

```ruby
# customer_event.rb
class CustomerEvent
  include BaseEvent

  attr_accessor :stripe_customer

  def initialize(stripe_customer)
    @stripe_customer = stripe_customer
  end

  def created
    # implement own logic...
  end

  def updated
    customer = Customer.find_by(stripe_id: stripe_customer.id)
    # implement own logic...
  end
end
```

and the whole point of this, is not having to use `.new` in initializers:

```ruby
# initializers/stripe.rb
StripeEvent.configure do |events|
  events.subscribe 'invoice.', InvoiceEvent
  events.subscribe 'customer.', CustomerEvent
end
```

Again, this is highly subjective, but I myself like this structure more 👍.

**Comment by timokleemann** [comment]
Why has this been downvoted...?

**Comment by tolgap** [comment]
@timokleemann Actually they were in the right to downvote that. My solution still had the same error after trying it out a few times... The issue is at constant level, and nothing to do with calling `.new`. I deleted it, because its misleading.
