### ISSUE TITLE
Signing Secret

### ISSUE THREAD

**Issue by rmaspero** [integrallis/stripe_event#111]
We were using the StripeEvent gem without the StripeEvent.signing_secret set as we wanted to accept them without it at least in development. But since one of the last updates I now get Bad Request 400 errors saying:

Cannot verify signature without a `StripeEvent.signing_secret`

The readme isn't clear if this is now required?

**Comment by rmm5t** [comment]
Hi @rmaspero. Yes, it is 100% required now. Please see the release notes for v2.0.0:

https://github.com/integrallis/stripe_event/releases/tag/v2.0.0
OR
https://github.com/integrallis/stripe_event/blob/master/CHANGELOG.md#200-december-14-2017

I'll tweak the README to make it more clear as well.
