### ISSUE TITLE
Stripe 4.x

### ISSUE THREAD

**Issue by AxelTheGerman** [integrallis/stripe_event#118]
Stripe recently released 4.x which dropped Ruby 2.0 support - I assume this lib doesn't support it officially either as it's EOL since 2016.

Would be great to allow `stripe_event` users to upgrade to latest 4.x `stripe`

Let me know if you'd like me to make a PR, thanks!

**Comment by excid3** [comment]
Agreed, we should get a new release cut for this soon so we can upgrade to stripe 4.x.

**Comment by invisiblefunnel** [comment]
> Let me know if you'd like me to make a PR, thanks!

Yes, please. Thanks!
