### ISSUE TITLE
Possible Misuse of ActiveSupport::Notifications

### ISSUE THREAD

**Issue by wagenet** [integrallis/stripe_event#121]
ActiveSupport::Notifications bills itself as providing ["an instrumentation API for Ruby"](https://api.rubyonrails.org/classes/ActiveSupport/Notifications.html). This usage of AS::N isn't for instrumentation. I'm also wondering just what benefit we really get from using AS::N here since we'll only ever have one event trigger in a request. I'm genuinely interested in finding a good solution for handling Stripe Webhooks and not duplicating someone else's work.

**Comment by invisiblefunnel** [comment]
Thanks for filing this issue.

>  what benefit we really get from using AS::N

Is this your question? I want to make sure I'm addressing your concerns.

**Comment by wagenet** [comment]
@invisiblefunnel thanks for the reply. That's probably the most important question here. This definitely seems like an off-label usage of AS::N, given that StripeEvent isn't an instrumentation library. However, I can understand that off-label usage might be acceptable if the benefits are high enough compared to the risks.

**Comment by invisiblefunnel** [comment]
@wagenet what are your specific concerns?

To set expectations, it's unlikely we're going to move away from `AS::N`.

**Comment by wagenet** [comment]
@invisiblefunnel I'm trying to understand why it was chosen given that this is definitely an off-label usage. Clearly, there was some benefit that you perceived which led you to choose it.

**Comment by invisiblefunnel** [comment]
`AS::N` provided a simple event dispatch mechanism. I have limited time to spend on open source so I'm going to close this issue rather than continuing the discussion.

**Comment by wagenet** [comment]
@invisiblefunnel thanks for your time. I genuinely considered using this library in a project of mine but decided against it due to the off-label usage of AS::N.

Furthermore, I am one of the primary developers on Skylight (https://skylight.io) and we rely on libraries correctly implementing AS::N for performance notifications. Seeing libraries using it in an off-label manner is concerning to me from this aspect as well.

I don't expect any further response, but just wanted to clarify that I have a real interest in this issue and am not just trolling.

**Comment by invisiblefunnel** [comment]
@wagenet good to hear. I suggest being more up-front with your concerns/intentions when filing issues like this. It would have been much easier to engage you in a meaningful conversation if your last comment had been the body of the issue.

**Comment by rmm5t** [comment]
Aside: Personally, this thread was confusing and difficult to follow for me. AS::N is a pub-sub implementation. This gem uses it as such. I'm not sure I ever understood the claim about "off-label" usage, and there was never a suggestion about alternative solutions -- just seemingly rhetorical questions about implementation decisions.

**Comment by wagenet** [comment]
@rmm5t

**Comment by wagenet** [comment]
@invisiblefunnel sorry about that!

@rmm5t the very first line of the AS::N description says it is an instrumentation library (https://api.rubyonrails.org/classes/ActiveSupport/Notifications.html). The primary method is called `instrument` as well. So while, yes, it is essentially a pub-sub library, it's certainly not intended for generic use.

**Comment by peterkeen** [comment]
Granted the docs say “intrumentation” but there’s nothing specific about AS::N that precludes using it as a general in-app pub sub system. 

Is there something about this gem’s usage that is causing an issue for Skylight today or is this a theoretical concern?

**Comment by wagenet** [comment]
At the moment it's a theoretical one. This is why I was asking earlier what the main benefit is from using AS::N for this job. It clearly works, but it's got an inherent fragility in that it's not being used for the intended use.

**Comment by wagenet** [comment]
To be clear, the two main theoretical concerns I have are:
1) If I were to use this library in my app, it could be unreliable since AS::N might make changes that are instrumentation focused that in some way cause trouble for this library, which is not instrumentation focused.
2) Skylight (and other instrumentation tools) assume that `AS::N.instrument` is being used for performance instrumentation reasons, since that is what the library says it is for. This library breaks that assumption.

**Comment by peterkeen** [comment]
The main benefit, as I see it, is that it’s a piece that’s built into Rails
that we don’t have to worry about because it just works. The claim that
such a use is fragile feels disingenuous to me. There are blog posts going
back at least 8 years describing this exact pattern. It’s extremely common
within larger Rails apps.

I think if Skylight depends on AS::N strictly being notifications then
you’re likely going to have to build in filtering. I don’t think policing
usage of the library is going to get the response you want.

**Comment by rmm5t** [comment]
> Skylight (and other instrumentation tools) assume that AS::N.instrument is being used for performance instrumentation reasons

Playing devil's advocate. If possible, and if stripe-event switched to relying on `AS::N.publish` instead of `AS::N.instrument`, would that solve the concerns?

**Comment by wagenet** [comment]
@rmm5t that _sounds_ better, but at the moment I don't know how the exact behavior would compare. I think it would still help me to feel a lot better if I saw the Rails team actually say "AS::N is a good pub-sub implementation, feel free to use it for that too". I work with one of the people who pushed for its inclusion in Rails years ago and instrumentation was definitely his goal, not a generic pub-sub implementation.

**Comment by wycats** [comment]
I'm also a developer on Skylight and the original designer of the AS::N system.

> I think if Skylight depends on AS::N strictly being notifications then you’re likely going to have to build in filtering

We do, of course, and I don't think we need to be worried about this kind of usage of AS::N disrupting Skylight directly.

I suspect that what @wagenet is getting at is that over the years, there have been changes to the nitty-gritty details of AS::N that caused us to have to change the internals of Skylight. In our case, we don't have much of a choice: we're trying to get information about Rails that isn't intrinsically a public API, so using AS::N is the most stable way we have to get at that information.

However, if you are using AS::N as a generic pub-sub system, some of the changes over the years might have affected you, which could also affect the stability of using the gem itself.

**Comment by invisiblefunnel** [comment]
Can this issue be closed?

**Comment by mhoad** [comment]
Just to hopefully help close this debate I wanted to point out that this specific concern has been addressed as a part of Rails 6. Details can be found here: https://github.com/rails/rails/pull/35705 but the TL;DR is that AS::N is now very much seen as something not limited to instrumentation use-cases.

**Comment by wagenet** [comment]
@mhoad thanks for pointing that out. My off-the-cuff personal opinion is that they should have made an underlying layer for pub-sub and built AS::N on top of that. But that's not what they did and that discussion isn't for here.
