### ISSUE TITLE
Stripe ruby gem v5.x

### ISSUE THREAD

**Issue by GuillaumeWrobel** [integrallis/stripe_event#125]
Hey @rmm5t ,

Stripe has released [v5 of the ruby gem](https://github.com/stripe/stripe-ruby/blob/master/CHANGELOG.md). Will open a PR when I have some time ahead.

Thx for the great open-source work!

**Comment by rmm5t** [comment]
@GuillaumeWrobel Thanks for the alert here. I'm working on a PR for this now.

**Comment by rmm5t** [comment]
🎉 stripe_event v2.3.0 released!
https://rubygems.org/gems/stripe_event
