### ISSUE TITLE
Remove the example with Stripe::Event.retrieve from README

### ISSUE THREAD

**Issue by bblimke** [integrallis/stripe_event#127]
I find the following example in REAMDE https://github.com/integrallis/stripe_event#configuration confusing.

````
StripeEvent.event_filter = lambda do |event|
  api_key = Account.find_by!(stripe_account_id: event.account).api_key
  Stripe::Event.retrieve(event.id, api_key)
end
````

There is no need to retrieve the event anymore since version 2.0.0,
as events are signed, yet the document suggests it's required.

**Comment by rmm5t** [comment]
Thanks for pointing that out. Readme updated.

**Comment by bblimke** [comment]
Excellent. Thank you!
