### ISSUE TITLE
Need to be able to differentiate between Stripe Connect customers and regular customers inside Stripe Events

### ISSUE THREAD

**Issue by TrevorHinesley** [integrallis/stripe_event#50]
`params[:user_id]` can be accessed easily inside an `event_retriever`, but not so easily inside of the subscribers. I have use cases where I'd like to send dispute emails for my own customers to my admin email, and send disputes for my Stripe Connect users' customers to the Stripe Connect user's email address for them to handle. This can't be differentiated inside of the `charge.dispute.created` namespace.

Would it be possible to make line 28 in `lib/stripe_event.rb` configurable (see below), similar to the configurable `event_retriever`?

https://github.com/integrallis/stripe_event/blob/master/lib/stripe_event.rb#L28

Two possibilities:

1. Allow extra parameters into the subscribe block, more than just the `event`?

2. Maybe just replace `event[:type]` with something configurable, so that if left default, it would pass `event[:type]`, but could be overridden to send something else (which would allow for further namespacing of subscribers)?

**Comment by TrevorHinesley** [comment]
#51

**Comment by rmm5t** [comment]
See my comment in #51:
https://github.com/integrallis/stripe_event/pull/51#issuecomment-72051385

**Comment by TrevorHinesley** [comment]
Thanks @rmm5t !
