### ISSUE TITLE
Can I use stripe_event in multiple gems? 

### ISSUE THREAD

**Issue by yas4891** [integrallis/stripe_event#52]
I want to replace the webhook management in koudoku (https://github.com/andrewculver/koudoku/) with stripe_event, but also use stripe_event in other gems that depend on koudoku (stripe_invoice and koudoku_coupons). 

Is this possible? 
Can I have multiple initializers that subscribe to stripe_event events or will they replace each other?

**Comment by peterkeen** [comment]
Yep, many subscribers can all receive the same event. `stripe_event` uses [ActiveSupport::Notifications](http://api.rubyonrails.org/classes/ActiveSupport/Notifications.html) under the hood.

**Comment by yas4891** [comment]
@peterkeen Would I have to add stripe_event routes to each gem/engine or can I just implement that in koudoku and have the others pick it up?
