### ISSUE TITLE
Disable retrieval?

### ISSUE THREAD

**Issue by julien51** [integrallis/stripe_event#61]
Is there any way to disable the retrieval of events when in tests/development? 
Some events are not easy to trigger from the Stripe interface like "customer.subscription.trial_will_end" using actual test data...

**Comment by rmm5t** [comment]
> Is there any way to disable the retrieval of events when in tests/development? 

Sure, but you're going to have to use [your own custom `EventRetriever`](https://github.com/integrallis/stripe_event#configuration) to change the specific behavior in your development environment.  

Of course, you should be able to mock this away just fine for your test environment. I use the stripe-ruby-mock to help with some of this while unit testing my stripe_event subscriptions.

**Comment by rmm5t** [comment]
Btw, please take any further questions like this to a site like [StackOverflow](http://stackoverflow.com/). GitHub Issues are best reserved for discussing feature requests and bug reports.
