### ISSUE TITLE
return non-200 code on any exception

### ISSUE THREAD

**Issue by toebbel** [integrallis/stripe_event#64]
Return 500 or similar when an exception (other than stripe auth exception) is thrown in user-code.

**Comment by rmm5t** [comment]
I'm not sure I'm following. Don't these exceptions from user-code already bubble up to the `StripeEvent::WebhookController` thereby triggering default `ActionController` behavior to return a 500 error?

**Comment by toebbel** [comment]
well okay then. Thanks - that helped :)
