### ISSUE TITLE
Rails 5 before_filter deprecation

### ISSUE THREAD

**Issue by mcolyer** [integrallis/stripe_event#69]
Rails is moving away from [*_filter](https://github.com/rails/rails/pull/18410) controller callbacks to `*_action`. Unfortunately `*_action` was only added in rails 4, but stripe_event currently supports `rails >= 3.1`.

I'd be willing to make a PR to change things but wasn't sure if backwards compatibility was required.

**Comment by invisiblefunnel** [comment]
@mcolyer a PR would be great!

Backwards compatibility is preferable, but not required. Would switching on `respond_to?(:before_action)` work?

Thank you.

**Comment by mcolyer** [comment]
Moving discussion over to #70.
