### ISSUE TITLE
does not support connected account webhooks

### ISSUE THREAD

**Issue by johnnagro** [integrallis/stripe_event#71]
Stripe has recently introduced the functionality that Platform accounts ("master" accounts) can retrieve events/receive webhooks pertaining to events taking place on it's connected accounts (managed or traditional connected accounts).

The primary difference in these events, is that they contain a ```user_id``` property, which needs to be included in the ```Stripe::Event.retrieve``` call [1]. If the receiver doesn't include this ```user_id``` in the event retrieval, it will result in a not-found, and thus a ```401``` back to stripe.

The proper way to retrieve an event for a connected account would look like this:

```ruby
Stripe::Event.retrieve(params[:id], stripe_account: params[:user_id])
```

So, the retrieve code in this library [2] can probably be updated to some variation of this:

```ruby
self.event_retriever = lambda { |params| params[:user_id].nil? ? Stripe::Event.retrieve(params[:id]) : Stripe::Event.retrieve(params[:id], stripe_account: params[:user_id]) }
```

I am happy to submit/start a PR but I'll likely need help with the impact on your test suite.

[1] [https://stripe.com/docs/connect/authentication#webhooks](https://stripe.com/docs/connect/authentication#webhooks)
[2] [https://github.com/dockwa/stripe_event/blob/master/lib/stripe_event.rb#L71](https://github.com/dockwa/stripe_event/blob/master/lib/stripe_event.rb#L71)

**Comment by rmm5t** [comment]
@johnnagro Are you saying that Stripe's changes simplify what we have written in the README here?
https://github.com/integrallis/stripe_event#configuration
i.e. Are you saying that you can now use the master API key to retrieve webhooks for subaccounts or Stripe Connected accounts?  

If answers are yes, this is interesting. My main concern with a change like this is managing some semblance of backwards compatibility. If I'm [reading the new Stripe Docs correctly](https://stripe.com/docs/connect/authentication#authentication-via-the-stripe-account-header), automatically doing this to the `retriever` might cause confusion if the old form of using an API key.  However, anyone using the old auth mechanism for subaccounts or connected accounts would have (should have?) already overridden the `event_retriever` with the old auth mechanisma anyway.

**Comment by johnnagro** [comment]
@rmm5t ah-hah. my bad for not reading that section more closely. it appears that i can take my proposed modification and toss it in there and i'm all good.... of course, i can do this because my event processor is expecting to see both kinds of events and you're correct in that making this the default behaviour might be confusing for folks...

So, I tried this and discovered something else which makes this whole decision murkier, ```user_id``` isn't included when _retrieving the event_ - only in the webhook payload. So, my code (which is now probably a little smellier) has look like:

```ruby
StripeEvent.event_retriever = lambda do |params|
  if params[:user_id].blank?
    return Stripe::Event.retrieve(params[:id])
  else
    evt = Stripe::Event.retrieve(params[:id], stripe_account: params[:user_id])
    evt['user_id'] = params[:user_id]
    return evt
  end
end
```

Ultimately, this snippet Works-On-My-Box™, so I'm happy. Sorry I didn't see the ```lambda``` thing sooner. How you want to support this in the future is up to you - I'm all good with where things stand now. 

Thanks for your help.
