### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by dnahodil** [integrallis/stripe_event#72]
Hi,

Just wanted to say thanks for making this library and making it available. It let me cut out a bunch of code for working with Stripe webhooks. I contacted Stripe and told them I'd wished they'd linked to this from their docs as I would have found it earlier and it would have saved me a bunch of time.

Cheers,
David

**Comment by rmm5t** [comment]
🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉
🎉🎉🎉❤️❤️❤️❤️❤️🎉🎉🎉❤️❤️❤️❤️❤️🎉🎉🎉
🎉🎉❤️❤️❤️❤️❤️❤️❤️🎉❤️❤️❤️❤️❤️❤️❤️🎉🎉
🎉❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️🎉
🎉❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️🎉
🎉❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️🎉
🎉🎉❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️🎉🎉
🎉🎉❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️🎉🎉
🎉🎉🎉❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️🎉🎉🎉
🎉🎉🎉🎉❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️🎉🎉🎉🎉
🎉🎉🎉🎉🎉❤️❤️❤️❤️❤️❤️❤️❤️❤️🎉🎉🎉🎉🎉
🎉🎉🎉🎉🎉🎉❤️❤️❤️❤️❤️❤️❤️🎉🎉🎉🎉🎉🎉
🎉🎉🎉🎉🎉🎉🎉❤️❤️❤️❤️❤️🎉🎉🎉🎉🎉🎉🎉
🎉🎉🎉🎉🎉🎉🎉🎉❤️❤️❤️🎉🎉🎉🎉🎉🎉🎉🎉
🎉🎉🎉🎉🎉🎉🎉🎉🎉❤️🎉🎉🎉🎉🎉🎉🎉🎉🎉
🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉
