### ISSUE TITLE
New gem version?

### ISSUE THREAD

**Issue by ajb** [integrallis/stripe_event#73]
It would be :bomb: to have https://github.com/integrallis/stripe_event/commit/f6e97b6cb14c103a0dd4cb5c52221cf1648e85b4 released as `1.5.1` for those of us using Rails 5.

Thanks for your consideration!

❤️

**Comment by rmm5t** [comment]
Sure. I'll try to get this released later today.

**Comment by rmm5t** [comment]
v1.5.1 released! Enjoy!

**Comment by ajb** [comment]
Thank you!
