### ISSUE TITLE
Stripe Events not in order

### ISSUE THREAD

**Issue by seraphimlord** [integrallis/stripe_event#75]
I noticed that sometimes the stripe events are not in order. For example, invoice.created maybe come at a later date after invoice.payment_succeeded and charge.succeeded.

I read that the only solution is to reject the webhooks and stripe will send them at a later date. How can do it with stripe_event?

**Comment by rmm5t** [comment]
Stripe will retry webhooks later after receiving something other than a `2xx` HTTP status code. More information about this (and the associated retry timing) can be found here:
https://stripe.com/docs/webhooks#responding-to-a-webhook

To return something other than a `200 OK` using stripe_event, you can raise an exception to trigger the included `WebhookController` to return a non-200 status code.

**Comment by rmm5t** [comment]
Btw, please take any further questions like this to a site like [StackOverflow](http://stackoverflow.com/). GitHub Issues are best reserved for discussing feature requests and bug reports.

**Comment by seraphimlord** [comment]
Thanks and noted
