### ISSUE TITLE
Newer version of stripe-ruby?

### ISSUE THREAD

**Issue by amedrz** [integrallis/stripe_event#82]
Hi guys,

[stripe-ruby](https://github.com/stripe/stripe-ruby) is at `v2.0.1` now and there have been a bunch of releases on their end during last year. 

Any chance we can support newer versions than `v1.6.x`.

Thanks in advance!

**Comment by rmm5t** [comment]
> Any chance we can support newer versions than v1.6.x.

Just to clarify, the gemspec supports v1.6 through v1.58. v2.0 was released two weeks ago. 

I can look at this later today or tomorrow, but if someone has the time to submit a green PR in the meantime, that would help too. Just comment here whoever starts work on this first.

**Comment by rmm5t** [comment]
Working on this now.

**Comment by amedrz** [comment]
Awesome! I really appreciate that @rmm5t 

Cheers!

**Comment by rmm5t** [comment]
No problem. There's a v1.6.0 out as well. 🍻 
https://rubygems.org/gems/stripe_event

**Comment by invisiblefunnel** [comment]
Thanks @rmm5t!
