### ISSUE TITLE
stripe gem version 3 compatiblity error

### ISSUE THREAD

**Issue by medBouzid** [integrallis/stripe_event#86]
Is there any chance to solve this : 

```
Bundler could not find compatible versions for gem "stripe":
  In snapshot (Gemfile.lock):
    stripe (= 3.0.0)

  In Gemfile:
    stripe (~> 3.0)

    stripe_event (~> 1.6) was resolved to 1.6.0, which depends on
      stripe (< 3.0, >= 1.6)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

**Comment by rmm5t** [comment]
@medBouzid There's now a (temporary) `86-stripe-v3-compatibility` branch and associated pull-request (#87). I'm going to let the test suite kick in to verify things and also let the PR sit for a bit allowing you to test against it. We can get a new official stripe_event version out soon after.
